### ISSUE TITLE
Problem during transform to tflite and ok in cloud environment training

### ISSUE THREAD

**Issue by momo1986** [titu1994/keras-efficientnets#22]
Hello, @titu1994 , thanks for your open-source project.

I build the training model successfully with your provided APIs in cloud environment.

However, when I transform to tflite model. It has problem.

My code is:
```
import tensorflow as tf
import keras
import h5py
import keras_efficientnets
from keras_efficientnets.config import BlockArgs, get_default_block_list
from keras_efficientnets.custom_objects import EfficientNetConvInitializer
from keras_efficientnets.custom_objects import EfficientNetDenseInitializer
from keras_efficientnets.custom_objects import Swish, DropConnect
if __name__ == "__main__":
    converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file("efficient_net_v1_190925.h5")
    converter.optimizations = [tf.contrib.lite.Optimize.OPTIMIZE_FOR_SIZE]
    tflite_model = converter.convert()
    open("efficient_net_wrap_finger.tflite", "wb").write(tflite_model)
```

The error-log is:

> Using TensorFlow backend.
> Traceback (most recent call last):
>   File "model_convert.py", line 10, in <module>
>     converter = tf.contrib.lite.TFLiteConverter.from_keras_model_file("efficient_net_v1_190925.h5")
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/lite/python/lite.py", line 368, in from_keras_model_file
>     keras_model = _keras.models.load_model(model_file)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 230, in load_model
>     model = model_from_config(model_config, custom_objects=custom_objects)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 310, in model_from_config
>     return deserialize(config, custom_objects=custom_objects)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
>     printable_module_name='layer')
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
>     list(custom_objects.items())))
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1292, in from_config
>     process_layer(layer_data)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1278, in process_layer
>     layer = deserialize_layer(layer_data, custom_objects=custom_objects)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
>     printable_module_name='layer')
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 175, in deserialize_keras_object
>     return cls.from_config(config['config'])
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1606, in from_config
>     return cls(**config)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py", line 488, in __init__
>     kernel_initializer=initializers.get(kernel_initializer),
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/initializers.py", line 155, in get
>     return deserialize(identifier)
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/initializers.py", line 147, in deserialize
>     printable_module_name='initializer')
>   File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 163, in deserialize_keras_object
>     raise ValueError('Unknown ' + printable_module_name + '

> : ' + class_name)
> ValueError: Unknown initializer: EfficientNetConvInitializer

What is the roor-cause of the problem?

How can I resolve it?

Or is there a bottleneck for the efficient-net model to be depolyed on mobile device?

Thanks & Regards!

**Comment by titu1994** [comment]
Two things. I think tflite is more for TF.keras than for core Keras, bit I may be wrong. If I'm wrong, then second thing is that I use custom initializers  which might not be detected by the tflite engine. If there is a way to pass custom objects to it, do that.
